// <auto-generated />
using System;
using LinkPulse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkPulse.Api.Data.Migrations
{
    [DbContext(typeof(LinkPulseDbContext))]
    partial class LinkPulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkPulse.Api.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_application_users_normalized_email");

                    b.ToTable("application_users", (string)null);
                });

            modelBuilder.Entity("LinkPulse.Api.Data.Entities.ClickEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_ip_hash");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("referrer");

                    b.Property<Guid>("ShortLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("short_link_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("ShortLinkId", "OccurredAt")
                        .HasDatabaseName("ix_click_events_short_link_id_occurred_at");

                    b.ToTable("click_events", (string)null);
                });

            modelBuilder.Entity("LinkPulse.Api.Data.Entities.ShortLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("short_code");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_url");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ux_short_links_short_code");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("ix_short_links_is_active_expires_at");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_short_links_owner_id_created_at");

                    b.ToTable("short_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_short_links_expiration", "expires_at IS NULL OR expires_at > created_at");

                            t.HasCheckConstraint("ck_short_links_short_code_not_empty", "char_length(short_code) > 0");
                        });
                });

            modelBuilder.Entity("LinkPulse.Api.Data.Entities.ClickEvent", b =>
                {
                    b.HasOne("LinkPulse.Api.Data.Entities.ShortLink", "ShortLink")
                        .WithMany("ClickEvents")
                        .HasForeignKey("ShortLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortLink");
                });

            modelBuilder.Entity("LinkPulse.Api.Data.Entities.ShortLink", b =>
                {
                    b.HasOne("LinkPulse.Api.Data.Entities.ApplicationUser", "Owner")
                        .WithMany("ShortLinks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LinkPulse.Api.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ShortLinks");
                });

            modelBuilder.Entity("LinkPulse.Api.Data.Entities.ShortLink", b =>
                {
                    b.Navigation("ClickEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
